apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: embedding-api-prod
resources:
  - ../../base
replicas:
  - name: embedding-api
    count: 2
configMapGenerator:
  - name: embedding-api-config
    behavior: merge
    literals:
      - ENVIRONMENT=prod
      - COLLECTION_PREFIX=docs-prod
      - MODEL_VERSION=v2
