apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: embedding-api-staging
resources:
  - ../../base
configMapGenerator:
  - name: embedding-api-config
    behavior: merge
    literals:
      - ENVIRONMENT=staging
      - COLLECTION_PREFIX=docs-staging
      - MODEL_VERSION=v1
